---
version: '2.1'
orbs:
  docker: circleci/docker@2.1.2
workflows:
  build-docker-image-only:
    jobs:
      - docker/publish:
          deploy: false
          image: $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME
...
