---
version: 2.1
orbs:
  docker: circleci/docker@2.1.2
workflows:
  build-and-push:
    jobs:
      - docker/publish:
          context:
            - docker
          dockerfile: Containerfile
          readme: README.adoc
          image: thekad/openvpn
          tag: latest
      - docker/publish:
          context:
            - quay
          dockerfile: Containerfile
          readme: README.adoc
          image: thekad/openvpn
          tag: latest
          registry: quay.io
...
