---
version: 2.1
orbs:
  docker: circleci/docker@2.1.2
workflows:
  build-docker-image-only:
    jobs:
      - docker/publish:
          context:
            - docker
          dockerfile: Containerfile
          readme: README.adoc
          image: thekad/openvpn
          tag: latest
...
